### ISSUE TITLE
Refresh button doesn't seem to work

### ISSUE THREAD

**Issue by balopat** [ZhangJian1713/vscode-image-viewer#20]
I love the UI of your VSCode Image Viewer plugin - it looks great. 

I tend to regenerate a lot of images in my workflow and inspect them. However, the panel does not refresh automatically. I'd be okay with pressing the reload/refresh button ![image](https://github.com/ZhangJian1713/vscode-image-viewer/assets/635073/456edaa0-b4ea-4eea-a71a-99d9edd093e6) but it doesn't seem to pick up the changes, I have to close and reopen the tab.

**Comment by balopat** [comment]
More precisely: the button works when there are new files or files are deleted. It doesn't seem to reload the image when only the contents change but the filename stays the same.

**Comment by ZhangJian1713** [comment]
I've fixed the issue. The problem was caused by the embedded webview browser using cached images by default(no new GET request), which was beneficial for performance but prevented updates. Now, it checks the file's modify time to determine whether to cache.
I'm glad this extension could help you, and I appreciate your feedback on the bug. Thank you!
